version: '3.8'

services:
  postgres-client:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=your_postgres_host
      - DB_NAME=your_database_name
      - DB_USER=your_database_user
      - DB_PASS=your_database_password
